CARD_DICT_PATH = "./cards.txt"
PRIORITY_CARD_DICT_PATH = "./priority_cards.txt"
TEST_CARD_DICT_PATH = "./test_cards.txt"
WORD_LEN_LIM = 30
UNICODE_CHINESE_LOWER_LIMIT = 19968
UNICODE_CHINESE_UPPER_LIMIT = 40959
ELEVEN_API_KEY = "sk_7c2dc4e759192fe01c07fd0d290d3e45ae126e8056ec838e"
ELEVEN_CHINESE_VOICE_ID = "hmD4OXeLrQIVXXUdliAG"
ELEVEN_API_URL = "https://api.elevenlabs.io/v1/text-to-speech/" + ELEVEN_CHINESE_VOICE_ID
AUDIO_PATH = "/Users/bryn/Documents/PyProjects/flashcards/output.mp3"